{% set version = "1.1.4" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-treeman
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/treeman_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/treeman/treeman_{{ version }}.tar.gz
  sha256: 3b11a72b012ed6edc1afee170ab7a0b7191f40197af3d4915546de4da74698e6

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-rjsonio
    - r-ape
    - r-bigmemory
    - r-plyr
    - r-stringr
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-rjsonio
    - r-ape
    - r-bigmemory
    - r-plyr
    - r-stringr

test:
  commands:
    - $R -e "library('treeman')"           # [not win]
    - "\"%R%\" -e \"library('treeman')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=treeman
  license: GPL-2.0-only
  summary: S4 class and methods for intuitive and efficient phylogenetic tree manipulation.
  license_family: GPL2
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: treeman
# Type: Package
# Title: Phylogenetic Tree Manipulation Class and Methods
# Version: 1.1.3
# Author: D.J. Bennett
# Maintainer: D.J. Bennett <dominic.john.bennett@gmail.com>
# Description: S4 class and methods for intuitive and efficient phylogenetic tree manipulation.
# License: GPL-2
# Depends: R (>= 3.2.4), methods
# Imports: plyr, ape, RJSONIO, stringr, bigmemory
# Suggests: testthat
# RoxygenNote: 6.0.1
# Collate: 'calc-methods.R' 'check_methods.R' 'cnvrt-methods.R' 'gen-methods.R' 'get-nd-methods.R' 'get-nds-methods.R' 'get-spcl-methods.R' 'manip-methods.R' 'ndlst-methods.R' 'ndmtrx-methods.R' 'node-declaration.R' 'read-write-methods.R' 'server-methods.R' 'set-methods.R' 'treeman-declaration.R' 'treemen-declaration.R' 'update-methods.R' 'viz-methods.R' 'zzz.R'
# NeedsCompilation: yes
# Packaged: 2018-09-17 10:21:24 UTC; dom
# Repository: CRAN
# Date/Publication: 2018-09-17 10:50:03 UTC
