{% set version = "1.1.3" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-treeman
  version: {{ version|replace("-", "_") }}

source:
  fn: treeman_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/treeman_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/treeman/treeman_{{ version }}.tar.gz
  sha256: d6fb714c8c3f88e8df1d644ebbbe1751c346de24ce21d2e46bab8d787ffc6a77

build:
  merge_build_host: True  # [win]
  number: 0
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-rjsonio
    - r-ape
    - r-bigmemory
    - r-plyr
    - r-stringr
  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-rjsonio
    - r-ape
    - r-bigmemory
    - r-plyr
    - r-stringr

test:
  commands:
    - $R -e "library('treeman')"           # [not win]
    - "\"%R%\" -e \"library('treeman')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=treeman
  license: GPL-2
  summary: S4 class and methods for intuitive and efficient phylogenetic tree manipulation.
  license_family: GPL2
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
