travis:
  secure:
    BINSTAR_TOKEN: kKG33qLuz/hX7FqGDa1hBYZ3tskyghT8WFl2yqWXsGN/Yo1ZAUxvb1eDsOriVWH+96l7FwrcJe1AQV3IUa3HFul/tylZGy3LydulwHwqN3HzIkOo59/R14ERotceHjEeLwda8RuggAaK+bSvU/TuAWyNncQleXkH5u0AaQ4VkNLX0bQ0VJTbZj6U85Dr2PP74jP3CcP2Ac7ek8L9XMZapIvYjgI7tlY/92ZIn2COacJXZnaaNY2fCD41rsHwsOG6c6cZDkiPbj6gKutY8lRYkZrLBQMKH/OGGW5XsGlEjen4I70pCVm/NMxebcuBn5svAgTlCJxpMn89nMcFdmeYumJehMAZ+mqjkC8GyLYhYxKyubVN7TIV9PKP6Eg1lxVG0yWUQRm2C5nacVU5vvbro8BjIIfUaZZ+7AqTzUpPW4pmGv1L+igHGUMnU7GPZnWjfzYWbqNr6+Y/0SfoK0gpUOvqInBWRcVGWpG2cF5mE2BmVNu85UvAl221H7JJRowCJSWv0PfEeBKv7FUmC2qIYrKhiwLZ5lthc4x/JeCQChqmYsH8dXmxr2UGlG8KlyfkJ5R04bvDb1QwONJTU9Lzisr5xU2vsHfbH79ZbMXs/7uYiMpa+Irx7fA81xbcZt5wT9k5A7fBq+6Q5tDu13f16rKgk5tEjTqx8yqZoU0q47s=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
